nav:
  - index.md
  - quickstart
  - models
  - demos
  - Documentation:
      - documentation/index.md
      - documentation/cli.md
      - API: api
      - Developer Guides:
          - developer_guides/index.md
          - "developer_guides/*.md"
          - Repository: repository
      - troubleshooting.md
  - community
