# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Model-neutral interactive driving application and session implementations."""

from __future__ import annotations

import argparse
import contextlib
import math
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from flashdreams.demo import (
    CanonicalInputSchema,
    CanonicalInputWindow,
    IFlashDreamsApplication,
    IFlashDreamsApplicationSession,
    SessionInfo,
)
from flashdreams.runtime import (
    DRIVER_COMMAND,
    InferenceConfig,
    InferenceInput,
    StepRequirements,
    StepResult,
    UserInputEvent,
    UserInputs,
)
from flashdreams.runtime.demo import PreparedScenario
from flashdreams.runtime.demo.session_inputs import UserInputWindow

from .post_processing import (
    InteractiveDriveUIState,
    build_interactive_drive_ui_pipeline,
)

AdapterFactory = Callable[[], Any]
ProviderFactory = Callable[..., Any]


@dataclass(frozen=True, kw_only=True, slots=True)
class InteractiveDriveScenarioOptions:
    """Model-neutral scene settings for one interactive driving session."""

    scene_path: Path | None
    """Optional path to one local scene asset."""

    scene_dir: Path | None
    """Optional directory containing local scene assets."""

    scene_uuid: str | None
    """Optional remotely discoverable scene identifier."""

    scene_variant: str
    """Visual variant of the selected scene."""

    camera_name: str
    """Camera rendered by the scene provider."""

    prompt: str | None
    """Optional model prompt override for the selected scene."""

    total_blocks: int
    """Maximum number of model chunks generated by the session."""

    pixel_height: int
    """Output frame height in pixels."""

    pixel_width: int
    """Output frame width in pixels."""

    fps: int
    """Presentation and control-sampling frame rate."""

    move_speed_per_s: float
    """Translation speed exposed to the scene provider."""

    rotate_speed_rad_per_s: float
    """Rotation speed exposed to the scene provider."""

    scene_backend: str
    """Rendering backend selected for the scene provider."""


ScenarioFactory = Callable[[InteractiveDriveScenarioOptions], Any]


@dataclass(frozen=True, kw_only=True, slots=True)
class InteractiveDriveApplicationDefaults:
    """Integration-provided defaults for an interactive driving application."""

    model_id: str
    """Model identifier passed to the FlashDreams inference runtime."""

    preset_id: str
    """Default integration-owned inference preset."""

    scenario_factory: ScenarioFactory
    """Factory that creates the integration's live driving scenario."""

    adapter_factory: AdapterFactory
    """Factory that creates the integration's FlashDreams demo adapter."""

    provider_factory: ProviderFactory
    """Factory that creates the integration's scene conditioning provider."""

    scene_uuid: str | None
    """Default remotely discoverable scene identifier."""

    pixel_height: int
    """Default output frame height in pixels."""

    pixel_width: int
    """Default output frame width in pixels."""

    device: str = "cuda"
    """Default device on which the model runtime is constructed."""

    seed: int = 42
    """Default inference seed."""

    scene_variant: str = "default"
    """Default visual variant of the selected scene."""

    camera_name: str = "camera_front_wide_120fov"
    """Default camera rendered by the scene provider."""

    total_blocks: int = 2_147_483_647
    """Default maximum number of model chunks in one session."""

    fps: int = 30
    """Default presentation and control-sampling frame rate."""

    move_speed_per_s: float = 6.0
    """Default translation speed used by the scene provider."""

    rotate_speed_rad_per_s: float = math.radians(35.0)
    """Default rotation speed used by the scene provider."""

    scene_backend: str = "cuda"
    """Default rendering backend used by the scene provider."""

    scene_backend_choices: tuple[str, ...] = ("cuda", "vulkan")
    """Rendering backends accepted by the application command line."""

    scene_backend_aliases: tuple[str, ...] = ()
    """Integration-specific aliases for the generic scene backend option."""

    ui_title: str = "INTERACTIVE DRIVE"
    """Title rendered in the presentation-only driving HUD."""


@dataclass(frozen=True, kw_only=True, slots=True)
class _InteractiveDriveSessionConfig:
    """Resolved settings for one interactive driving session."""

    inference_config: InferenceConfig
    """Integration-owned model and runtime selection."""

    scenario_options: InteractiveDriveScenarioOptions
    """Model-neutral scene settings selected for this session."""

    show_ui: bool
    """Whether generated chunks receive the presentation HUD."""

    ui_title: str
    """Integration-provided title rendered in the presentation HUD."""

    scenario_factory: ScenarioFactory
    """Factory that converts shared scene settings into an integration scenario."""

    adapter_factory: AdapterFactory
    """Factory that creates the integration's FlashDreams demo adapter."""

    provider_factory: ProviderFactory
    """Factory that creates the integration's scene conditioning provider."""


class InteractiveDriveApplication(IFlashDreamsApplication):
    """Reusable interactive driving application configured by one integration."""

    session_type: type["InteractiveDriveApplicationSession"]

    def __init__(self, *, defaults: InteractiveDriveApplicationDefaults) -> None:
        self.defaults = defaults
        self._session_config: _InteractiveDriveSessionConfig | None = None

    @property
    def input_schema(self) -> CanonicalInputSchema:
        """Request transport-neutral steering, throttle, and brake levels."""
        return CanonicalInputSchema(
            modalities=(DRIVER_COMMAND,),
            description="Interactive driving controls.",
        )

    def init(self, commandline_args: Sequence[str]) -> None:
        """Parse scene and runtime options for one interactive driving run."""
        parser = argparse.ArgumentParser(prog="flashdreams-run interactive-drive")
        parser.add_argument("--preset-id", default=self.defaults.preset_id)
        parser.add_argument("--device", default=self.defaults.device)
        parser.add_argument("--seed", type=int, default=self.defaults.seed)
        parser.add_argument("--scene-path", type=Path)
        parser.add_argument("--scene-dir", type=Path)
        parser.add_argument("--scene-uuid", default=self.defaults.scene_uuid)
        parser.add_argument("--scene-variant", default=self.defaults.scene_variant)
        parser.add_argument("--camera-name", default=self.defaults.camera_name)
        parser.add_argument("--prompt")
        parser.add_argument(
            "--total-blocks", type=int, default=self.defaults.total_blocks
        )
        parser.add_argument(
            "--pixel-height", type=int, default=self.defaults.pixel_height
        )
        parser.add_argument(
            "--pixel-width", type=int, default=self.defaults.pixel_width
        )
        parser.add_argument("--fps", type=int, default=self.defaults.fps)
        parser.add_argument(
            "--move-speed-per-s",
            type=float,
            default=self.defaults.move_speed_per_s,
        )
        parser.add_argument(
            "--rotate-speed-rad-per-s",
            type=float,
            default=self.defaults.rotate_speed_rad_per_s,
        )
        parser.add_argument(
            "--scene-backend",
            *self.defaults.scene_backend_aliases,
            dest="scene_backend",
            choices=self.defaults.scene_backend_choices,
            default=self.defaults.scene_backend,
        )
        parser.add_argument(
            "--ui",
            action=argparse.BooleanOptionalAction,
            default=True,
            help="render the driving HUD through presentation post-processing",
        )
        args = parser.parse_args(list(commandline_args))

        if args.total_blocks <= 0:
            raise ValueError("--total-blocks must be greater than zero.")
        if args.pixel_height <= 0 or args.pixel_width <= 0:
            raise ValueError("--pixel-height and --pixel-width must be positive.")
        if args.fps <= 0:
            raise ValueError("--fps must be greater than zero.")
        if args.move_speed_per_s <= 0 or args.rotate_speed_rad_per_s <= 0:
            raise ValueError("Interactive-drive movement speeds must be positive.")

        self._session_config = _InteractiveDriveSessionConfig(
            inference_config=InferenceConfig(
                model_id=self.defaults.model_id,
                preset_id=args.preset_id,
                device=args.device,
                seed=args.seed,
                runtime_options={"seed": args.seed},
            ),
            scenario_options=InteractiveDriveScenarioOptions(
                scene_path=args.scene_path,
                scene_dir=args.scene_dir,
                scene_uuid=args.scene_uuid,
                scene_variant=args.scene_variant,
                camera_name=args.camera_name,
                prompt=args.prompt,
                total_blocks=args.total_blocks,
                pixel_height=args.pixel_height,
                pixel_width=args.pixel_width,
                fps=args.fps,
                move_speed_per_s=args.move_speed_per_s,
                rotate_speed_rad_per_s=args.rotate_speed_rad_per_s,
                scene_backend=args.scene_backend,
            ),
            show_ui=args.ui,
            ui_title=self.defaults.ui_title,
            scenario_factory=self.defaults.scenario_factory,
            adapter_factory=self.defaults.adapter_factory,
            provider_factory=self.defaults.provider_factory,
        )

    def create_session(self) -> IFlashDreamsApplicationSession:
        """Create a cache-isolated interactive driving session."""
        if self._session_config is None:
            raise RuntimeError(
                "InteractiveDriveApplication.init() must run before create_session()."
            )
        return self.session_type(config=self._session_config)


class InteractiveDriveApplicationSession(IFlashDreamsApplicationSession):
    """Bridge canonical controls into an integration-owned model runtime."""

    def __init__(self, *, config: _InteractiveDriveSessionConfig) -> None:
        self.config = config
        self._runtime: Any | None = None
        self._model_session: Any | None = None
        self._provider: Any | None = None
        self._held_keys: frozenset[str] = frozenset()
        self._input_time_s = 0.0
        self._closed = False

    def init(self) -> None:
        """Create the model runtime, scene provider, and model session."""
        if self._closed:
            raise RuntimeError("Cannot initialize a closed interactive-drive session.")
        if self._model_session is not None:
            return

        scenario = self.config.scenario_factory(self.config.scenario_options)
        inference_config = self.config.inference_config
        prepared_scenario = PreparedScenario(
            initial_inputs=InferenceInput(
                global_conditioning={"scenario": scenario},
            ),
            metadata={
                "model_id": inference_config.model_id,
                "preset_id": inference_config.preset_id,
                "num_views": 1,
            },
        )

        adapter = self.config.adapter_factory()
        runtime = adapter.create_runtime(inference_config)
        provider = None
        try:
            provider = self.config.provider_factory(
                scenario=prepared_scenario,
                config=inference_config,
            )
            initial_input = provider.prepare_initial_input()
            model_session = runtime.start_session(initial_input)
        except BaseException:
            if provider is not None:
                with contextlib.suppress(Exception):
                    provider.close()
            with contextlib.suppress(Exception):
                runtime.close()
            raise
        self._runtime = runtime
        self._provider = provider
        self._model_session = model_session

    def session_info(self) -> SessionInfo:
        """Describe the unmodified model video stream to output sinks."""
        self._require_initialized()
        inference_config = self.config.inference_config
        scenario_options = self.config.scenario_options
        return SessionInfo(
            output_layout="bvtchw",
            frames_per_second=float(scenario_options.fps),
            video_width=scenario_options.pixel_width,
            video_height=scenario_options.pixel_height,
            metadata={
                "application": "interactive-drive",
                "model_id": inference_config.model_id,
                "preset_id": inference_config.preset_id,
            },
        )

    def next_step_requirements(self) -> StepRequirements | None:
        """Forward the next chunk requirements authored by the model."""
        if self._closed:
            return None
        return self._require_model_session().next_step_requirements()

    def step(self, inputs: CanonicalInputWindow) -> StepResult:
        """Condition and generate one model chunk from canonical controls."""
        model_session = self._require_model_session()
        provider = self._require_provider()
        requirements = model_session.next_step_requirements()
        if requirements is None:
            raise RuntimeError("Interactive-drive session has no remaining steps.")
        command = _driver_command_from_inputs(inputs)
        keys = _keys_from_driver_command(command)
        window_end_s = self._input_time_s + requirements.input_frame_count / float(
            self.config.scenario_options.fps
        )
        events = _key_transition_events(
            previous=self._held_keys,
            current=keys,
            timestamp_s=self._input_time_s,
        )
        prepared = provider.prepare_step(
            request=requirements,
            user_window=UserInputWindow(
                start_s=self._input_time_s,
                end_s=window_end_s,
                inputs=UserInputs(events=events),
            ),
        )
        if prepared.control.close_session or prepared.control.reset:
            raise RuntimeError(
                prepared.control.reason
                or "The conditioning provider stopped interactive-drive."
            )
        if prepared.inference_input is None:
            raise RuntimeError("The conditioning provider emitted no input.")

        result = model_session.step(prepared.inference_input)
        if self.config.show_ui:
            result = result.register_post_processing_pipeline(
                build_interactive_drive_ui_pipeline(
                    InteractiveDriveUIState.from_driver_command(
                        command,
                        source=_input_source(inputs),
                        title=self.config.ui_title,
                    )
                ),
                requirements.step_index,
            )
        self._held_keys = keys
        self._input_time_s = window_end_s
        return result

    def close(self) -> None:
        """Release provider state before the parent model runtime."""
        if self._closed:
            return
        self._closed = True
        model_session, self._model_session = self._model_session, None
        provider, self._provider = self._provider, None
        runtime, self._runtime = self._runtime, None
        if model_session is not None:
            with contextlib.suppress(Exception):
                model_session.close()
        if provider is not None:
            with contextlib.suppress(Exception):
                provider.close()
        if runtime is not None:
            with contextlib.suppress(Exception):
                runtime.close()

    def _require_initialized(self) -> None:
        self._require_model_session()
        self._require_provider()

    def _require_model_session(self) -> Any:
        if self._closed:
            raise RuntimeError("Interactive-drive session is closed.")
        if self._model_session is None:
            raise RuntimeError(
                "InteractiveDriveApplicationSession.init() must run before use."
            )
        return self._model_session

    def _require_provider(self) -> Any:
        if self._closed:
            raise RuntimeError("Interactive-drive session is closed.")
        if self._provider is None:
            raise RuntimeError(
                "InteractiveDriveApplicationSession.init() must run before use."
            )
        return self._provider


InteractiveDriveApplication.session_type = InteractiveDriveApplicationSession


def _driver_command_from_inputs(inputs: CanonicalInputWindow) -> dict[str, Any]:
    value = inputs.values.get(DRIVER_COMMAND.name)
    if not isinstance(value, Mapping):
        raise ValueError("interactive-drive requires canonical driver_command input.")
    return dict(DRIVER_COMMAND.value(value))


def _keys_from_driver_command(command: Mapping[str, Any]) -> frozenset[str]:
    if bool(command.get("stop", False)):
        return frozenset()
    keys: set[str] = set()
    throttle = float(command.get("throttle", 0.0))
    brake = float(command.get("brake", 0.0))
    steer = float(command.get("steer", 0.0))
    reverse = bool(command.get("reverse", False))
    if throttle > 0.01:
        keys.add("s" if reverse else "w")
    if brake > 0.01:
        keys.add("s")
    if steer > 0.01:
        keys.add("a")
    elif steer < -0.01:
        keys.add("d")
    return frozenset(keys)


def _key_transition_events(
    *,
    previous: frozenset[str],
    current: frozenset[str],
    timestamp_s: float,
) -> tuple[UserInputEvent, ...]:
    released = (
        UserInputEvent(
            timestamp_s=timestamp_s,
            event_type="keyup",
            payload={"key": key},
            source="canonical-driver-command",
        )
        for key in sorted(previous - current)
    )
    pressed = (
        UserInputEvent(
            timestamp_s=timestamp_s,
            event_type="keydown",
            payload={"key": key},
            source="canonical-driver-command",
        )
        for key in sorted(current - previous)
    )
    return (*released, *pressed)


def _input_source(inputs: CanonicalInputWindow) -> str:
    sources = inputs.metadata.get("canonical_sources")
    if isinstance(sources, Mapping):
        value = sources.get(DRIVER_COMMAND.name)
        if isinstance(value, str):
            return value
    return "input"


__all__ = [
    "InteractiveDriveApplication",
    "InteractiveDriveApplicationDefaults",
    "InteractiveDriveApplicationSession",
    "InteractiveDriveScenarioOptions",
]
